### ISSUE TITLE
Test Docker Container

### ISSUE THREAD

**Issue by jbelmont** [jbelmont/docker-workshop#1]
@charlieduong94 and @nzmoore when you get a chance could you test this

**Comment by ctdio** [comment]
I'll see if I can test this later tonight.

**Comment by jbelmont** [comment]
great thanks @charlieduong94

**Comment by nzmoore** [comment]
Jean-Marcel
I was able to test and run this successfully.
I did the following:
git clone git@github.com:jbelmont/docker-workshop.git
cd docker-workshop/
npm run build
npm run dev

This all worked without errors and the application was running and accessible at http://localhost:3000 <http://localhost:3000/>

I also spent some time getting this to run on my own environment which was a bit more involved.


Regards Bill Moore
bill@nzmoore.com

**Comment by jbelmont** [comment]
Fantastic thank you @nzmoore as this helps tremendously. I will be adding more things such as mgo (mongodb code) and redis for go but that shouldn't affect the workshop
