### ISSUE TITLE
Separating Dockerfile into 2 separate Dockerfiles one for frontend and for backend

### ISSUE THREAD

**Issue by jbelmont** [jbelmont/docker-workshop#2]
At the suggestion of the docker slack group I am separating out the Dockerfile into 2 different instances to be consumed at the docker-compose.yml. The reason being is that the frontend is using webpack and vue.js and the backend is using golang and the ports and other things were clashing. I am currently trying to fix issues but if you can see anything I am doing wrong that would great.
@charlieduong94 and @nzmoore if you all could check out the latest changes and let me know what you think?

**Comment by jbelmont** [comment]
What is happening currently is that `session, err = mgo.Dial("dockerworkshop_db_1")` is not connecting to mongodb and is getting `Panic: no reachable servers`? I should be able to do this `session, err = mgo.Dial(os.Getenv("MONGO_URL")) from the environment variables in docker-compose.yml but that is not working.

**Comment by nzmoore** [comment]
Jean Marcel
I am not very familiar with Docker nor Golang, but I have spent time working with this, but I can’t get the application to run.
I can do npm run build and nom run dev without any obvious errors but cannot access the app.
All the containers start successfully and I don’t get the Mongo error you report.

How is the app meant to be accessed?
When I try localhost:3000 no data is ever returned.

I spent some time trying to understand the ports exposed from the containers but I am not sure I understand how you intended this to work?

Regards Bill Moore
919 413 6213
bill@nzmoore.com
linkedin.com/in/billmoore

**Comment by jbelmont** [comment]
@nzmoore I am thinking this could be multiple things I added `/usr/local/var/mongodb` to file sharing volume in docker app for mac, I wonder if windows needs something equivalent mapped in file sharing. I am going to have to play with this some more. `MGO` mongodb is a real pain to connect it seems.

**Comment by jbelmont** [comment]
One command I am doing a lot is `docker rmi $(docker images --filter "dangling=true" -q --no-trunc)` and I am also using the Kitematic Container application in mac os x. It might have to specify an actual container name in docker-compose.yml

**Comment by jbelmont** [comment]
Closing this because I moved the logic for this into another repository and this will be bite sized code examples for the workshop which I think will work better
